name: update rsshub docs

on:
  schedule:
    - cron: '0 0 * * MON'  # run on Monday of each week

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the RSSHub repo
        uses: actions/checkout@v2
        with:
          repository: DIYgod/RSSHub
          path: rsshub-app
          # fetch-depth: 0 # Fetch all history
      
      - name: checkout this repo and update the docs
        uses: actions/checkout@v2
        with:
          path: rsshub-docs
          fetch-depth: 0  # Fetch all history
        run: |
          cp -r rsshub-app/docs rsshub-docs/docs
          cd rsshub-docs
          git config user.name SylleoYr
          git config user.email SylleoYr@users.noreply.github.com
          git add .
          git commit -m "Docs updated by GitHub Actions"
          git push -u origin master