name: update rsshub docs

on:
  push:
    
  schedule:
    - cron: '0 0 * * MON'  # run on Monday of each week

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the RSSHub repo
        uses: actions/checkout@v2
        with:
          repository: DIYgod/RSSHub
          path: rsshub-app
          # fetch-depth: 0 # Fetch all history
      
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: rsshub-docs
          fetch-depth: 0  # Fetch all history
      
      - name: copy the updated docs
        run: |
          cp -r rsshub-app/docs rsshub-docs/
          cp rsshub-app/package.json rsshub-docs/
          cp rsshub-app/yarn.lock rsshub-docs/
          cp rsshub-app/LICENSE rsshub-docs/
          cd rsshub-docs
          sh check_update.sh
